Dev 533 transform javascript where function to fql
Etesie/fauna-typed pull request #10
Opened 2024-07-16 09:46 UTC by firehudson

2024-07-16 10:10 UTC, firehudson commented
**Regarding Sonar Issue:** This is expected as we have to use `Function` constructor to convert string function to callable function.

Currently, we are passing a valid fauna query string from client side for `where` predicate function, please check [here](https://github.com/Etesie/fauna-typed/blob/DEV-533-transform-javascript-where-function-to-fql/src/routes/cms/client/table/%2Bpage.svelte#L37-L47). 

To run this predicate function's string in document store to get data from store's state we convert string to function using `Function` constructor, please check [here](https://github.com/Etesie/fauna-typed/blob/DEV-533-transform-javascript-where-function-to-fql/src/lib/stores/document.svelte.ts#L186).

To strictly check of where predictable function's string, we are using ``(item) => ${string}`` typescript type instead of  `string`, please check [here](https://github.com/Etesie/fauna-typed/blob/DEV-533-transform-javascript-where-function-to-fql/src/lib/stores/document.svelte.ts#L34)

If above solution looks good to you @mmailaender , Should we apply `where` method's predicate function type to Collection store's `where` method as well?

2024-07-17 06:33 UTC, mmailaender requested changes

2024-07-17 06:33 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> -	where: (filter: Predicate<Document<T>>) => Page<Functions<T, T_Replace, T_Update>>;
Are you aware of what you have done here? Please explain the implications to me.

2024-07-17 10:55 UTC, mmailaender requested changes

2024-07-17 10:55 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +					return (filter: Predicate<Document<MainType>> | `(item) => ${string}`) => {
Bad practice - The API is accepting only `filter: Predicate<Document<MainType>>` - accepting different types inside the proxy will create Type errors.

2024-07-17 11:12 UTC, firehudson commented on src/lib/stores/document.svelte.ts
> +					return (filter: Predicate<Document<MainType>> | `(item) => ${string}`) => {
Okay, let me update `filter: Predicate<Document<MainType>>` to `filter: Predicate<Document<MainType>> | '(item) => ${string}'`. By using this type user will have both options to pass predicate as string or function

2024-07-17 11:34 UTC, mmailaender requested changes

2024-07-17 11:34 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +					return (filter: Predicate<Document<MainType>> | `(item) => ${string}`) => {
There are multiple parties: 
`Client` -> `Fauna Typed API` -> `ETL` -> `Fauna API`, and they should not be mixed.
The API provides a clean and concise typed API. In our case, it expects a function of type `Predicate<Document<MainType>>`, and the ETL takes care of transforming it into an FQL Function. But what you are doing is, allowing the Client to pass a typed Function AND a string. That makes the API overloaded and unclear to a consumer and deprives the ELT of its function.

2024-07-18 15:30 UTC, mmailaender approved these changes

2024-07-18 15:30 UTC, merged