Dev 545 fauna support for by
Etesie/fauna-typed pull request #19
Opened 2024-07-30 05:07 UTC by firehudson

2024-07-31 08:30 UTC, mmailaender requested changes

2024-07-31 08:30 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +	const createDocumentHandler = (doc: Record<string, any> = {}) => {
Replace with `const createDocumentHandler = (id: string)`

2024-07-31 08:30 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +						const latestData = current.find((doc) => doc.id === args[0]) || {
Move into createDocumentHandler

const existingDoc = $state(current.find((doc) => doc.id === args[0])) || {});

2024-07-31 08:30 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +				// Special handling for accessing the whole object
Here you need to put the code from byId

```
const existingDoc = $state(current.find((doc) => doc.id === args[0])) || {});
db.byId(args[0]);
```

2024-07-31 08:30 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +				if (prop in doc) {
doc becomes `existingDoc`

2024-08-13 06:10 UTC, firehudson commented on src/lib/database/fauna.ts
> +			console.error('Error fetching document from database using byId:', error);
We have handled this case in try block. If document not found, fauna returns `cause: "not found"` in response.

Should we need to delete from store if API fails (from catch block)?

![image](https://github.com/user-attachments/assets/b3d793a6-375b-459a-ac9f-194053e1179b)

2024-08-16 09:31 UTC, mmailaender requested changes
Please deal with my comments, resolve them if they are outdated and explain what have change since the last time.

2024-08-16 09:31 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +	const createDocumentHandler = (doc: Record<string, any> = {}) => {
push

2024-08-16 10:36 UTC, firehudson commented on src/lib/stores/document.svelte.ts
> +	const createDocumentHandler = (doc: Record<string, any> = {}) => {
We can't find document inside createDocumentHandler function from `current` state using below code. Because this is causing call stack error. We need to pass complete document object from parameter instead of document ID

```const existingDoc = $state(current.find((doc) => doc.id === args[0])) || {}); db.byId(args[0]);```

2024-08-16 10:38 UTC, firehudson commented on src/lib/stores/document.svelte.ts
> +						const latestData = current.find((doc) => doc.id === args[0]) || {
Can't move `const existingDoc = $state(current.find((doc) => doc.id === args[0])) || {});` into createDocumentHandler. The reason is same as above

2024-08-16 10:39 UTC, firehudson commented on src/lib/stores/document.svelte.ts
> +				// Special handling for accessing the whole object
Can't do that, Same reason as above

2024-08-16 10:44 UTC, firehudson commented on src/lib/stores/document.svelte.ts
Yes there was call stack error. Find document by Id inside createDocumentHandler function creates this error. I've explained this in detail in discord channel.

https://discord.com/channels/1222455699146018816/1273168077034360853

2024-08-16 10:46 UTC, firehudson commented
> Please deal with my comments, resolve them if they are outdated and explain what have change since the last time.

We can't use `current` state inside createDocumentHandler function to find document. This is causing re-rending and call stack error. So I direct pass document from parameter instead of ID.

2024-08-17 08:24 UTC, mmailaender requested changes
I'm getting still the error "RangeError: Maximum call stack size exceeded"

2024-08-20 05:12 UTC, firehudson commented on src/lib/stores/collection.svelte.ts
> -const createDocumentHandler = (name: string) => {
To fix maxsize call stack error, Pass document object instead of name as a parameter

2024-08-20 05:38 UTC, firehudson commented on src/lib/stores/collection.svelte.ts
> -			const latestData = $state(getObjects((doc) => doc.name === name).at(0) || {});
To fix maxsize call stack error, Remove state from handler function

2024-08-21 06:49 UTC, mmailaender requested changes
With the latest change, the story is almost returned to the start of the story. The whole idea was to have for .byName and .byId lazy loading and with the latest change the lazy loading is rolled back. 

You can check it by cleaning cache and localstorage and reloading.

2024-08-21 12:43 UTC, firehudson commented on src/lib/stores/document.svelte.ts
> -	const definition = Collection.byName(COLL_NAME);
Remove definition variable from `createDocumentStore` function's body and use `Collection.byName(COLL_NAME)` directly at the place of definition variable, please check [here](https://github.com/Etesie/fauna-typed/pull/19/files#diff-3bdb63643a18a300365f108844246e13e2f20707372749f3e2aa5d51d04bcafcR230) for more clarity

2024-08-21 15:44 UTC, firehudson commented on src/lib/stores/document.svelte.ts
> +					return CollectionStore.byName(COLL_NAME);
Currently It's working, Could you please check it by taking pull on local and clear local storage?

Although, I'm trying to find alternative of this

2024-08-21 15:58 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +					return CollectionStore.byName(COLL_NAME);
If it currently works, then only because you have a lucky race condition. But it can't solve layze fetching conceptual side @firehudson

2024-09-17 07:26 UTC, closed without merging