WIP: Dev 515 generate types from fauna schema
Etesie/fauna-typed pull request #3
Opened 2024-06-26 06:18 UTC by firehudson

2024-06-27 19:27 UTC, manansoni77 commented on src/lib/database/fetchSchema.svelte.ts
> +					signature: 'Number'
The name of the doc field is 'birthdate' here is used 'birthday'

2024-06-27 19:29 UTC, manansoni77 commented on src/lib/database/fetchSchema.svelte.ts
> +					signature: 'Number'
Also birthdate has been made an array, which means it will not work here.

2024-06-27 19:30 UTC, manansoni77 commented on src/lib/database/fetchSchema.svelte.ts
> +				},
Is this Array of dates intentional? It seems misleading, specially with the fieldname.

2024-06-27 19:32 UTC, manansoni77 commented on src/lib/types/generated/types.ts
> +	account?: Account;
This field was compulsory before, it has now become optional.

2024-06-27 19:32 UTC, manansoni77 commented on src/lib/types/generated/types.ts
> +	account?: DocumentReference;
Same as above, this field was compulsory before, it has now become optional.

2024-06-27 19:33 UTC, manansoni77 commented on src/lib/types/generated/types.ts
>  };
Similar to above, Account has fields which were compulsory before, but have now become optional.

2024-06-27 19:35 UTC, manansoni77 approved these changes
Added some comments regarding generated types which are different from before. Also, please checkout the sonar security issue.

2024-06-28 05:15 UTC, firehudson commented on src/lib/database/fetchSchema.svelte.ts
> +					signature: 'Number'
I made it intentionally to check functionality for array type of data

2024-06-28 05:17 UTC, firehudson commented on src/lib/database/fetchSchema.svelte.ts
> +				},
It's intentional, will undo after take review by mike

2024-06-28 05:17 UTC, firehudson commented on src/lib/types/generated/types.ts
> +	account?: Account | DocumentReference;
For the optional key, We have schema file(created by mike) and in that, some fields are optional therefore it's updated in types file

2024-06-28 05:18 UTC, firehudson commented on src/lib/types/generated/types.ts
> +	account?: Account;
Same as above

2024-06-28 05:18 UTC, firehudson commented on src/lib/types/generated/types.ts
> +	account?: DocumentReference;
Same as above

2024-06-28 05:19 UTC, firehudson commented on src/lib/types/generated/types.ts
>  };
Same as above

2024-06-28 05:40 UTC, manansoni77 commented on src/lib/database/fetchSchema.svelte.ts
> +					signature: 'Number'
Array is okay, but what about the field name which is different in the function body?

2024-06-28 06:04 UTC, manansoni77 commented on src/lib/database/fetchSchema.svelte.ts
> +					signature: 'Date'
I think we should stick with birthdate here, as that was the name originally, and update the fn body to match it.
Or, if you are sure on renaming the field here, it may need to be done in more places. One of which is
store-document.svelte.ts line 466

2024-06-28 06:29 UTC, firehudson commented on src/lib/database/fetchSchema.svelte.ts
> +					signature: 'Date'
I'm not sure about it, @mmailaender Could you please suggest, what should be the key name for birthday?

2024-06-28 06:55 UTC, mmailaender commented on src/lib/database/fetchSchema.svelte.ts
> +					signature: 'Date'
Why do we have this discussion @firehudson? The test schema was already defined upfront by me.

2024-06-28 06:58 UTC, mmailaender commented on src/lib/database/fetchSchema.svelte.ts
> +				},
If you want to have an array, then let's use account because to be precisely a user can have multiple ones. 

```
account: {
	signature: 'Array<Ref<Account>>?'
}
```

2024-06-28 07:00 UTC, mmailaender commented on src/lib/types/generated/types.ts
> +	account?: Account;
This is a generated file. The only question that we have: "Is it matching the definition?"

2024-06-28 07:43 UTC, mmailaender requested changes

2024-06-28 07:43 UTC, mmailaender commented on src/lib/database/fetchSchema.svelte.ts
Not needed. The schema will be fetched from <collection>.definition https://github.com/Etesie/fauna-typed/blob/main/src/lib/stores/store-document.svelte.ts#L34

2024-06-28 07:43 UTC, mmailaender commented on generateTypes.ts
> +	return value.endsWith('?');
`?` is not every time at the end:
`optionalArrayNumber: Array<Number?>`

2024-06-28 07:43 UTC, mmailaender commented on generateTypes.ts
> +	return value.startsWith(expectedType);
This is not supporting Tuples: ` creationTime: Time | Number`

2024-06-28 07:43 UTC, mmailaender commented on generateTypes.ts
> +	signatureType: 'Ref' | 'Array',
You only need Ref - An array is also wrapping a Ref if we're talking about a collection name

2024-06-28 07:43 UTC, mmailaender commented on generateTypes.ts
> +const createInterface = (
This generates a type definition string, but not an interface

2024-06-28 07:43 UTC, mmailaender commented on generateTypes.ts
> +		const schema = await fetchSchema();
Collection.all()

2024-06-28 09:10 UTC, firehudson commented on generateTypes.ts
> +	signatureType: 'Ref' | 'Array',
This is to support Array<Ref<Collection>>.
Example - `Array<Ref<Account>>?` in the user schema

2024-06-28 09:18 UTC, firehudson commented on generateTypes.ts
> +	return value.endsWith('?');
What should be the end result of the above in typescript @mmailaender 

It can translated to - `optionalArrayNumber?: Array<Number>`
here `optionalArrayNumber` is optional and all items in array are always optional in typescript. Empty array is also supported by same syntax

If there's a case where the array can be mix of provided type and null e.g. [1,2,3, [Null](https://docs.fauna.com/fauna/current/reference/fql_reference/types#null), 5]
In this case, fauna deletes the items.

let me know if we can finalize `optionalArrayNumber?: Array<Number>`

2024-06-28 09:19 UTC, firehudson commented on src/lib/database/fetchSchema.svelte.ts
Got it. I need to first merge the #2 to get collection store here

2024-06-28 09:26 UTC, mmailaender commented on generateTypes.ts
> +	signatureType: 'Ref' | 'Array',
But why it matters? You run `.match()` and the return value of the function is only if the signature has a ref or not in both cases (Array or non array)

2024-06-28 09:30 UTC, mmailaender commented on generateTypes.ts
> +	return value.endsWith('?');
We can skipt it - Although tuple is described in their docs, its not yet supported in schema enforcement

2024-06-28 11:30 UTC, firehudson commented on generateTypes.ts
> +	return value.startsWith(expectedType);
Updated 
![image](https://github.com/Etesie/fauna-typed/assets/18103669/6d97432b-574e-455d-b987-2733e27b65f6)

2024-07-01 11:21 UTC, mmailaender requested changes

2024-07-01 11:21 UTC, mmailaender commented on src/routes/+layout.svelte
> +	import { onMount } from 'svelte';
onMount is deprecated by $effect https://component-party.dev/compare/svelte4-vs-svelte5#dom-ref & https://svelte-5-preview.vercel.app/docs/runes#$effect

2024-07-01 11:21 UTC, mmailaender commented on src/routes/api/types/+server.ts
That way you can't use the fauna-typed library in our repositories without also adding this route to every repository. Please move the code to lib/types

The code needs to work independently of routes

2024-07-01 11:21 UTC, mmailaender commented on src/routes/+layout.svelte
1. That way, you can't use the fauna-typed library in our repositories without adding this code to every repository layout file. 

2. As discussed before, and documented in $lib/stores/index.ts, it makes probably sense to integrate the generation into the index.ts.

2024-07-01 11:25 UTC, mmailaender commented on src/routes/+layout.svelte
> +			const genetatedTypesRes = await res.json();
Typo => generatedTypesRes

2024-07-01 12:19 UTC, firehudson commented on src/routes/+layout.svelte
I thought so, this will do after Type Converter story, but let me complete now

2024-07-03 07:03 UTC, mmailaender approved these changes
Will be followed up by https://etesie.atlassian.net/browse/DEV-525

2024-07-03 07:19 UTC, merged