Dev 498 type converter
Etesie/fauna-typed pull request #4
Opened 2024-06-26 06:26 UTC by manansoni77

2024-06-26 07:09 UTC, mmailaender commented on src/lib/types/converters/createToDoc.ts
> +export const createToDoc = <
docCreateToDoc is more explicit without being to verbose

2024-06-28 09:43 UTC, mmailaender requested changes

2024-06-28 09:43 UTC, mmailaender commented on src/lib/stores/store-document.svelte.ts
> +			docCreateToDoc(doc, definition, COLL_NAME),
Use the new definition object, that includes name (definition.name) from main branch - so you can get rid of COLL_NAME

2024-06-28 09:43 UTC, mmailaender commented on src/lib/types/default/types.ts
Get rid of Definition - it get's replaced by the type `Collection`. You can pull it from Main

2024-07-05 11:42 UTC, mmailaender requested changes

2024-07-05 11:42 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +			docUpdateToDoc(doc, fields, definition);
This violates the single responsible pattern. docUpdateToDoc should only do the conversion and not the update of the object.

2024-07-05 11:42 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +			docReplaceToDoc(doc, fields, definition);
Same as for docUpdateToDoc

2024-07-05 11:42 UTC, mmailaender commented on src/lib/types/converters/docCreateToDoc.ts
> +export const docCreateToDoc = <K extends keyof TypeMapping>(
no need for TypeMapping - The user never sees the typing. Please follow the generic pattern with 
```
<
MainType extends QueryValueObject, 
CreateType extends QueryValueObject, 
ReplaceType extends QueryValueObject, 
UpdateType  extends QueryValueObject
```

2024-07-05 11:42 UTC, mmailaender commented on src/lib/types/converters/docCreateToDoc.ts
> +			if (field.signature === 'Number') {
Why are you validating here for `Number`?

2024-07-05 11:42 UTC, mmailaender commented on src/lib/types/converters/docCreateToDoc.ts
You're not converting references `Ref<>` to `() => <>.byId("")`

2024-07-05 11:48 UTC, firehudson requested changes

2024-07-05 11:48 UTC, firehudson commented on src/lib/types/converters/docUpdateToDoc.ts
> +	});
Why are you deleting a key from doc?

2024-07-05 11:48 UTC, firehudson commented on src/lib/types/converters/docUpdateToDoc.ts
> +	Object.assign(doc, updatedFields);
For the best practices, you should create a new doc variable, then pass it to Object.assign. As Object.assign method mutate the original object and this can lead to a bug.

2024-07-05 11:48 UTC, firehudson commented on src/lib/types/converters/docReplaceToDoc.ts
> +	Object.assign(doc, updatedFields);
For the best practices, you should create a new doc variable, then pass it to Object.assign. As Object.assign method mutate the original object and this can lead to a bug.

2024-07-05 14:12 UTC, mmailaender commented on src/lib/types/converters/docUpdateToDoc.ts
> +	Object.assign(doc, updatedFields);
Which bug you are referring to? @firehudson  🤔

2024-07-08 05:56 UTC, firehudson commented on src/lib/types/converters/docUpdateToDoc.ts
> +	Object.assign(doc, updatedFields);
There may be a possibility, from the client side pass **state** or **default value's object** which is using at other place also at client side, so by our code that object will be updated or key will be deleted by below code(from line 17-23 in file), and that might be create some problem in future

```
Object.keys(doc).forEach((key) => {
  if (!(key in updatedFields)) {
    if (key !== 'ts') {
    delete doc[key];
    }
  }
});
```

2024-07-08 06:03 UTC, firehudson commented on src/lib/types/converters/docUpdateToDoc.ts
> +	Object.assign(doc, updatedFields);
Sorry, here should not create any bug as we are mutating internal state. 

@manansoni77 leave it

2024-07-08 09:20 UTC, manansoni77 commented on src/lib/types/converters/docCreateToDoc.ts
> +			if (field.signature === 'Number') {
Checking if the computed field is a number then setting it to 0, else setting it to an empty string.

2024-07-08 09:41 UTC, manansoni77 commented on src/lib/types/converters/docUpdateToDoc.ts
> +	});
Because update doc does not need this key, 'ts' will be provided by fauna when it is updated in the database.

2024-07-08 12:18 UTC, firehudson commented on src/lib/types/converters/docUpdateToDoc.ts
> +	});
You are deleting the keys which does not exist in `updatedFields` object and not a `ts` key. and by using `delete` keyword key will be delete from store state's object

2024-07-08 12:26 UTC, firehudson requested changes

2024-07-08 12:49 UTC, mmailaender requested changes

2024-07-08 12:49 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +			docUpdateToDoc(doc, fields, definition);
This is still not solved. You need to do Object.assign with the converted doc, not with the initial one. The current way docUpdateToDoc is useless🙂

2024-07-08 12:49 UTC, mmailaender commented on src/lib/types/converters/docCreateToDoc.ts
> +			if (field.signature === 'Number') {
What if it's Time, Date, etc? https://docs.fauna.com/fauna/current/reference/fql_reference/types

2024-07-08 12:49 UTC, mmailaender commented on src/lib/types/converters/docCreateToDoc.ts
> +	const convertedDoc: any = { id, ts, coll, ...computed_fields };
If you want to type it, this is better: `const convertedDoc = { id, ts, coll, ...computed_fields } as Document<T>;` and then changing the function signature to this:

```
export const docCreateToDoc = <T extends QueryValueObject, T_Create extends QueryValueObject>
```

With that you leverage the already existing type system.

2024-07-09 06:20 UTC, firehudson commented on src/lib/types/converters/docUpdateToDoc.ts
> +	});
I can't see any updates for this @manansoni77

2024-07-09 06:22 UTC, firehudson commented on src/lib/types/converters/docReplaceToDoc.ts
> +			}
Refactor this condition for all fauna types, as you did in `src/lib/types/converters/docCreateToDoc.ts` file

2024-07-09 06:26 UTC, firehudson requested changes
Please resolve above changes.

Also please check this [thread](https://github.com/Etesie/fauna-typed/pull/4#discussion_r1666698621)

2024-07-09 11:06 UTC, firehudson requested changes

2024-07-09 11:06 UTC, firehudson commented on src/lib/types/converters/docReplaceToDoc.ts
You're not converting references `Ref<>` to `() => <>.byId("")`

2024-07-09 11:06 UTC, firehudson commented on src/lib/types/converters/docUpdateToDoc.ts
You're not converting references `Ref<>` to `() => <>.byId("")`

2024-07-09 11:50 UTC, firehudson approved these changes

2024-07-09 14:39 UTC, mmailaender commented on src/lib/types/converters/docCreateToDoc.ts
> +		if (val?.id) {
Why are you not going via the key? We know that masterQuestion is a reference from definition. @firehudson

2024-07-09 15:26 UTC, mmailaender requested changes

2024-07-09 15:26 UTC, mmailaender commented on src/lib/types/converters/docCreateToDoc.ts
> +	const convertedDoc: any = { id, ts, coll, ...docValues, ...computed_fields };
You can simplify it: `return { id, ts, coll, ...docValues, ...computed_fields } as Document<T>`

2024-07-09 15:26 UTC, mmailaender commented on src/lib/types/converters/getDocumentWithoutReference.ts
Maybe something like transformFaunaRefToStoreFunctions

```
/**
* Transforms all Fauna References to store functions for a given object.
*/
```

2024-07-09 15:26 UTC, mmailaender commented on src/lib/types/converters/docReplaceToDoc.ts
> +	const updatedFieldsWithoutReference = getDocumentWithoutReference(updatedFields, definition, s);
keep the naming consistent. Here: `updatedFieldsWithoutReference`; In docCreatToDoc: `docValues`

2024-07-09 15:26 UTC, mmailaender commented on src/lib/types/converters/docReplaceToDoc.ts
> +	const convertedDoc: any = {
You can simplify it: 
```ts
return {
		id: doc.id,
		ts: doc.ts,
		coll: doc.coll,
		...updatedFieldsWithoutReference,
		...computed_fields
}; as Document<T>
```

2024-07-09 15:26 UTC, mmailaender commented on src/lib/types/converters/docUpdateToDoc.ts
> +	const convertedDoc: any = { ts: doc.ts, ...updatedFieldsWithoutReference, ...computed_fields };
same as above - simplicity

2024-07-09 15:26 UTC, mmailaender commented on src/lib/types/converters/docUpdateToDoc.ts
> +	const updatedFieldsWithoutReference = getDocumentWithoutReference(updatedFields, definition, s);
same as above - consistency

2024-07-09 15:31 UTC, manansoni77 commented on src/lib/stores/document.svelte.ts
>  			Object.assign(doc, fields);
The object.assign line was supposed to be deleted, because currently it is overwriting the doc which we get from the converter which defeats the purpose entirely.

2024-07-09 18:19 UTC, mmailaender commented on src/lib/types/converters/getDocumentWithoutReference.ts
Please also add the tsdoc

2024-07-09 18:27 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
>  			Object.assign(doc, fields);
I asked you to explain to me the three lines on purpose, but you didn't - so I will formulate it more straightforward: 
1. Your code is buggy and won't work
2. your task is to read about object references and what happens if you try to update them via `=` or `Object.assign` 
3. Tell me your findings
4. Tell me the bug
5. Fix it

2024-07-10 05:10 UTC, manansoni77 commented on src/lib/stores/document.svelte.ts
>  			Object.assign(doc, fields);
If you assign an object reference via "=" it creates a new object and saves it's reference in the variable.
If you use "Object.assign" it updates the existing object in the reference
The original code for "updateObject" was returning the doc, so I figured it would not make much difference if we instead created and returned a new doc, but upon further inspection I noticed that that was not the case as the returned value was not assigned anywhere. This means that the functions "updateObject" and "replaceObject" need to be making changes to doc directly (inplace).
To do this we need to something like
```js
const converted = docUpdateToDoc(doc, fields, definition, s);
Object.assign(doc, converted)
```

2024-07-10 05:36 UTC, manansoni77 commented on src/lib/types/converters/docReplaceToDoc.ts
> +	const updatedFieldsWithoutReference = getDocumentWithoutReference(updatedFields, definition, s);
In "docCreateToDoc" we pass the whole doc, thus it is named "documentFieldsWithoutReference", while in "docUpdateToDoc" and "docReplaceToDoc" we pass only updatedFields so it is named "updatedFieldsWithoutReference".

2024-07-10 06:45 UTC, mmailaender requested changes

2024-07-10 06:45 UTC, mmailaender commented on src/lib/types/converters/docReplaceToDoc.ts
> +	T extends QueryValueObject,
Instead of mixing T and MainType, you only need T:
```
<
T extends QueryValueObject,
T_Replace extends QueryValueObject,
T_Update extends QueryValueObject
>
```

2024-07-10 06:45 UTC, mmailaender commented on src/lib/types/converters/docUpdateToDoc.ts
> +	ReplaceType extends QueryValueObject
Same as above
Instead of mixing T and MainType, you only need T:
```
<
  T extends QueryValueObject,
  T_Replace extends QueryValueObject,
  T_Update extends QueryValueObject
>
```

2024-07-10 06:45 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +		let doc = current.find((u) => $state.is(u.id, id));
const

2024-07-10 06:45 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +		let doc = current.find((u) => $state.is(u.id, id));
const

2024-07-10 06:45 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
>  			Object.assign(doc, fields);
Exactly 👍

2024-07-10 06:45 UTC, mmailaender commented on src/lib/types/converters/docReplaceToDoc.ts
> +	const updatedFieldsWithoutReference = getDocumentWithoutReference(updatedFields, definition, s);
if you follow this logic, then you need to change it to `replacedFieldsWithoutReference`

2024-07-11 06:23 UTC, mmailaender approved these changes

2024-07-11 11:01 UTC, merged