Dev 511 document t t document create t t fauna create
Etesie/fauna-typed pull request #5
Opened 2024-07-03 05:40 UTC by firehudson

2024-07-05 14:24 UTC, mmailaender requested changes
Why is this existing as standalone Pull request and not as part of DEV-498?

2024-07-05 14:24 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +const CollectionStore = createCollectionStore();
The name `Collection` was on purpose to stick in the Fauna conventions, why are you changing it?

2024-07-08 05:37 UTC, firehudson commented on src/lib/stores/document.svelte.ts
> +const CollectionStore = createCollectionStore();
This file have a `let Collection` variable(at line 24) and `type Collection` (at line 14), by using same name for different cases, typescript generates warning, that's why I renamed Collection variable with CollectionStore

2024-07-08 05:42 UTC, firehudson commented
> Why is this existing as standalone Pull request and not as part of DEV-498?

To differentiate Manan and My code, I created a separate PR. Also that helps Manan and me to review each other's PR

2024-07-08 07:25 UTC, mmailaender commented
> > Why is this existing as standalone Pull request and not as part of DEV-498?
> 
> To differentiate Manan and My code, I created a separate PR. Also that helps Manan and me to review each other's PR

Then please resolve first Manan's PR and apply the findings also to your PR :)

2024-07-11 13:49 UTC, manansoni77 approved these changes

2024-07-12 08:32 UTC, manansoni77 commented on src/lib/stores/document.svelte.ts
>  	): Functions<MainType, ReplaceType, UpdateType> => {
Hey @firehudson , why have you changed the type here?

2024-07-12 08:34 UTC, manansoni77 commented on src/lib/stores/document.svelte.ts
> +
Is this faunadoc required?

2024-07-12 08:35 UTC, manansoni77 commented on src/lib/types/converters/toFaunaDoc.ts
> +	}
Can you explain the need for this condition?

2024-07-12 08:38 UTC, manansoni77 commented on src/lib/types/converters/toFaunaValue.ts
> +		return value.id && value?.coll?.name
Update this condition to what was discussed in the earlier PR to check for valid reference

2024-07-12 08:39 UTC, manansoni77 commented on src/lib/util.ts
> +	return twMerge(clsx(inputs));
Please reformat this file to original way, as it will be easier to go through.

2024-07-12 08:41 UTC, manansoni77 reviewed
Please go through the comments, and also resolve conflicts.

2024-07-15 06:11 UTC, firehudson commented on src/lib/types/converters/toFaunaValue.ts
> +		return value.id && value?.coll?.name
I've already handle condition to check reference type in the parent function from where it's calling. Please go through the `toFaunaValue` function in same file.

Here I'm handling only fallback, if user passes empty object in that case it will return `null`

2024-07-15 06:14 UTC, firehudson commented on src/lib/types/converters/toFaunaDoc.ts
> +	}
From the story description,
![image](https://github.com/user-attachments/assets/a2805dd1-32b2-44f8-b801-8a00bdcd3938)

We should not send the doc id which is created with `TEMP_` prefix.  To handle this edge case I added this condition

2024-07-15 06:16 UTC, firehudson commented on src/lib/stores/document.svelte.ts
> +
Not getting you point, Could you please explain it?

2024-07-19 17:37 UTC, mmailaender requested changes

2024-07-25 07:04 UTC, mmailaender approved these changes

2024-07-25 07:51 UTC, merged