Add after method which supports local store cursor
Etesie/fauna-typed pull request #7
Opened 2024-07-11 11:50 UTC by manansoni77

2024-07-11 16:08 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +						if (target?.after && typeof target?.after === 'number') {
example for a cursor `after: "hdWCxmVFdmVudIHKhGNhbGyA9PaAgc1KBYgPCOWwAMoEL8GCGmaQA14aE6tmgBA="`

2024-07-22 18:17 UTC, mmailaender requested changes

2024-07-22 18:17 UTC, mmailaender commented on src/lib/types/types.ts
> +	localCursor?: number;
If you introduce here `localCursor` it means it appears as part of intellisense `User.all()` which is confusing to the consumer, because it's information that should be not exposed via API

2024-07-22 18:17 UTC, mmailaender commented on src/lib/types/types.ts
> +	updateAfter = (after: Promise<string | void | undefined>) => {
same as `localCursor`

2024-07-23 07:01 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +							result.updateAfter(
by using 
```
result.after = fetchPaginatedFromDB(result, after).then(
									(res) => res,
									(e) => console.log(e)
								)
```
you already can  get rid of  `updateAfter`

2024-07-23 08:08 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +								current.slice(pageSize * cursor, pageSize * (cursor + 1)),
```ts
const data= current.slice(pageSize * cursor, pageSize * (cursor + 1))
const localCursor = {
  cursor: current.length > pageSize * (cursor + 1) ? cursor + 1 : undefined
}

new Page<Functions<MainType, ReplaceType, UpdateType>>(data, localCursor)
localCursor.cursor = //newValue
```

```
class Page<T extends QueryValueObject> {
	public data: T[];
	#localCursor?: {};
```

2024-07-23 08:11 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +								current.slice(pageSize * cursor, pageSize * (cursor + 1)),
https://github.com/Etesie/fauna-typed/blob/main/src/lib/stores/collection.svelte.ts#L39

2024-07-23 19:00 UTC, mmailaender requested changes

2024-07-23 19:00 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
>  	async function fetchAllFromDB(page: Page<Functions<MainType, ReplaceType, UpdateType>>) {
This is long ago deprecated code - please get the latest version from main

2024-07-23 19:00 UTC, mmailaender commented on src/lib/stores/document.svelte.ts
> +	async function fetchPaginatedFromDB(
see my comment for fetchAllFromDB - fetchPaginatedFromDB should not exist in document.svelte.ts - Instead it will be handled from database/fauna.ts (Clear responsibilities)

2024-07-23 19:00 UTC, mmailaender commented on src/lib/types/types.ts
> +	after?: Promise<string | undefined | void>;
why the return value `void`?

2024-07-26 06:30 UTC, manansoni77 commented on src/lib/types/types.ts
> +	after?: Promise<string | undefined | void>;
Because after string also has this type, it can resolve to string | undefined and if the after call is not valid it returns void, thus it can be assigned these 3 types.

2024-07-26 07:06 UTC, mmailaender commented on src/lib/types/types.ts
> +	after?: Promise<string | undefined | void>;
Please elaborate a bit more on "after call is not valid"

2024-07-29 06:39 UTC, mmailaender requested changes

2024-07-29 06:39 UTC, mmailaender commented on src/lib/types/types.ts
> +	after?: Promise<string | undefined>;
I'm realizing at this moment that the after type is overall wrong. In the current case, after returns a string or undefined. This is how Fauna works, but then you need to fetch also the data with the help of the cursor and `Set.paginate()` data. 

In our case, we want to include the fetching directly into `after`, so we need to change the response value to `Page<T>`. We also skip the Promise because we do optimistic fetching.

So we replace it with `after?: `Page<T>` and the proxy returns optimistically the new data from the cache and lazily updates from Fauna. If Fauna includes a cursor again, we set asynchronously  `after` in the new returned `Page`.

2024-07-29 07:36 UTC, mmailaender commented on src/lib/types/types.ts
> +	after?: Promise<string | undefined>;
$state(page.cursor)

2024-08-03 15:30 UTC, mmailaender requested changes

2024-08-03 15:30 UTC, mmailaender commented on src/lib/types/types.ts
> +	afterCursor?: string;
afterCursor needs to be private to not appear in the Type intellisense.

2024-08-03 15:30 UTC, mmailaender commented on src/lib/types/types.ts
> +	after?: Page<T>;
some thoughts: if after is a function, it could access the private afterCursor, but then we need to change the API for `after` to `after()`.

Alternatively, I see the option to keep `after` as a prop, but for that, we need to replace the class with two types: external and internal.

The external one exposes `data`, `after` and the internal one `data`, `after`, and `afterCursor`.

2024-08-16 09:18 UTC, mmailaender requested changes

2024-08-16 09:18 UTC, mmailaender commented on src/lib/types/types.ts
> +// This PageType is used to expose the Page object to the client.
Use jsdoc syntax to comment appear in the intellisense doc. 
/**
 *
 */

2024-08-16 09:18 UTC, mmailaender commented on src/lib/types/types.ts
> +type PageType<T extends QueryValueObject> = {
If you use the type `PageType` and `PageInternal`, there is no need anymore for a class. It's duplicated. Either use the class for internal and remove the type `PageInternal` or vice versa.

2024-08-16 13:22 UTC, mmailaender approved these changes

2024-08-17 08:24 UTC, mmailaender approved these changes

2024-08-20 05:16 UTC, merged